### PR TITLE
REALMC-8206: Bump version to 1.3.0

### PR DESCRIPTION
**Pull request by UnicodeSnowman**

### CODE REVIEW

**Review by andrewzlchen — APPROVED** [review]
lgtm!

**Comment by andrewzlchen** [comment]
I see that @makesitgo has an open PR as well, so maybe we can batch his changes with this version bump if needed?

**Comment by UnicodeSnowman** [comment]
> I see that @makesitgo has an open PR as well, so maybe we can batch his changes with this version bump if needed?

@andrewzlchen those changes are going into the `next` branch though, not `master`. are these changes of yours needed for the current release of the CLI? or the upcoming/yet to be released version 2.0 of the CLI?

**Comment by andrewzlchen** [comment]
oh whoops, sorry didnt realize that. I need these changes to be on the current (to-be legacy) version of the realm cli.

**Pull request merged**
